//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsGH.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WsGH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   add SupplyData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextAddSupplyData {
            get {
                return ResourceManager.GetString("LoggingTextAddSupplyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fix PositionShifting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextFixPS {
            get {
                return ResourceManager.GetString("LoggingTextFixPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   for Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextForTwitter {
            get {
                return ResourceManager.GetString("LoggingTextForTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found PositionShifting! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextFoundPS {
            get {
                return ResourceManager.GetString("LoggingTextFoundPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   get Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextGetPosition {
            get {
                return ResourceManager.GetString("LoggingTextGetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save Screenshot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextGetScreenshot {
            get {
                return ResourceManager.GetString("LoggingTextGetScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextrBackground {
            get {
                return ResourceManager.GetString("LoggingTextrBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read SupplyData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextReadSupplyData {
            get {
                return ResourceManager.GetString("LoggingTextReadSupplyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save SupplyData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextSaveSupplyData {
            get {
                return ResourceManager.GetString("LoggingTextSaveSupplyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextScene {
            get {
                return ResourceManager.GetString("LoggingTextScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   try fix PositionShifting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoggingTextTryFixPS {
            get {
                return ResourceManager.GetString("LoggingTextTryFixPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About...(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderAbout {
            get {
                return ResourceManager.GetString("MenuHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderAction {
            get {
                return ResourceManager.GetString("MenuHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderBackground {
            get {
                return ResourceManager.GetString("MenuHeaderBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderBackgroundOther {
            get {
                return ResourceManager.GetString("MenuHeaderBackgroundOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderEnglishLanguage {
            get {
                return ResourceManager.GetString("MenuHeaderEnglishLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderExit {
            get {
                return ResourceManager.GetString("MenuHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   for Twitter(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderForTwitter {
            get {
                return ResourceManager.GetString("MenuHeaderForTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Position(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderGetPosition {
            get {
                return ResourceManager.GetString("MenuHeaderGetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Screenshot(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderGetScreenshot {
            get {
                return ResourceManager.GetString("MenuHeaderGetScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderHelp {
            get {
                return ResourceManager.GetString("MenuHeaderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese(_J) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderJapaneseLanguage {
            get {
                return ResourceManager.GetString("MenuHeaderJapaneseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderOption {
            get {
                return ResourceManager.GetString("MenuHeaderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderSelectLanguage {
            get {
                return ResourceManager.GetString("MenuHeaderSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show pic Folder(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderShowPicFolder {
            get {
                return ResourceManager.GetString("MenuHeaderShowPicFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Window(_W) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderShowWindow {
            get {
                return ResourceManager.GetString("MenuHeaderShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SupplyWindow(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderSupplyWindow {
            get {
                return ResourceManager.GetString("MenuHeaderSupplyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimerWindow(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHeaderTimerWindow {
            get {
                return ResourceManager.GetString("MenuHeaderTimerWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ocr_template {
            get {
                object obj = ResourceManager.GetObject("ocr_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Diamond に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyChartY2Title {
            get {
                return ResourceManager.GetString("SupplyChartY2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fuel, Ammo, Steel, Bauxite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyChartYTitle {
            get {
                return ResourceManager.GetString("SupplyChartYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ammo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyTypeAmmo {
            get {
                return ResourceManager.GetString("SupplyTypeAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bauxite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyTypeBauxite {
            get {
                return ResourceManager.GetString("SupplyTypeBauxite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diamond に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyTypeDiamond {
            get {
                return ResourceManager.GetString("SupplyTypeDiamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fuel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyTypeFuel {
            get {
                return ResourceManager.GetString("SupplyTypeFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupplyTypeSteel {
            get {
                return ResourceManager.GetString("SupplyTypeSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bld に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlockTextBld {
            get {
                return ResourceManager.GetString("TextBlockTextBld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlockTextDev {
            get {
                return ResourceManager.GetString("TextBlockTextDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlockTextDock {
            get {
                return ResourceManager.GetString("TextBlockTextDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlockTextExp {
            get {
                return ResourceManager.GetString("TextBlockTextExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextGetPositionButton {
            get {
                return ResourceManager.GetString("TextGetPositionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScreenShot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextScreenShotButton {
            get {
                return ResourceManager.GetString("TextScreenShotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SupplyWindow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleSupplyWindow {
            get {
                return ResourceManager.GetString("TitleSupplyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TimerWindow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleTimerWindow {
            get {
                return ResourceManager.GetString("TitleTimerWindow", resourceCulture);
            }
        }
    }
}
